[package]
name = "include-dir"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]

[dependencies]
include-dir-derive = { path = "include-dir-derive" }
include-dir-macro = { path = "include-dir-macro" }